language: cpp
sudo: required
dist: trusty

compiler:
  - gcc
  - clang

branches:
  only:
    - master

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y                                      # GCC 7
  - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main' -y # Clang 5.0
  - sudo apt-get update
  - sudo apt-get install -y --allow-unauthenticated g++-7 clang-5.0
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-5.0 60 --slave /usr/bin/clang++ clang++ /usr/bin/clang++-5.0
  - sudo apt-get install -y --allow-unauthenticated libboost-all-dev libgfortran3 gfortran openmpi-bin openmpi-common openmpi-doc libopenmpi-dev libblas-dev liblapack-dev libfftw3-dev libgmp-dev hdf5-tools libhdf5-serial-dev python-h5py python-dev python-numpy python-scipy python-jinja2 python-matplotlib ipython python-mpi4py python-mako clang-format-5.0 libclang-5.0-dev python-clang-5.0 libnfft3-dev libeigen3-dev

install: true

script:
  # Stop on first error
  - set -e

  # Create directory for installed prerequisites
  - export PREREQS_DIR=$(readlink -f $TRAVIS_BUILD_DIR/../installed)
  - mkdir $PREREQS_DIR

  # Install cpp2py
  - cd $TRAVIS_BUILD_DIR/..
  - git clone https://github.com/TRIQS/cpp2py.git cpp2py.git
  - pushd cpp2py.git && git checkout master && popd
  - mkdir cpp2py.build && pushd cpp2py.build
  - |
    cmake ../cpp2py.git -DCMAKE_CXX_COMPILER=/usr/bin/${CXX} \
    -DPYTHON_INTERPRETER=/usr/bin/python \
    -DCMAKE_INSTALL_PREFIX=$PREREQS_DIR
  - make -j3 install
  - source $PREREQS_DIR/share/cpp2pyvars.sh

  # Build and install TRIQS
  - cd $TRAVIS_BUILD_DIR/..
  - git clone https://github.com/TRIQS/triqs.git triqs.git
  - pushd triqs.git && git checkout unstable && popd
  - mkdir triqs.build && pushd triqs.build
  - |
    cmake ../triqs.git \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_INSTALL_PREFIX=$PREREQS_DIR \
    -DCMAKE_CXX_COMPILER=/usr/bin/${CXX} \
    -DBuild_Documentation=OFF \
    -DBuild_Tests=OFF
  - make -j3 install
  - source $PREREQS_DIR/share/triqsvars.sh

  # Build and install Pomerol
  - cd $TRAVIS_BUILD_DIR/..
  - git clone https://github.com/aeantipov/pomerol.git pomerol.git
  - pushd pomerol.git && git checkout master && popd
  - mkdir pomerol.build && pushd pomerol.build
  - |
    cmake ../pomerol.git \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_INSTALL_PREFIX=$PREREQS_DIR \
    -DCMAKE_CXX_COMPILER=/usr/bin/${CXX} \
    -DTesting=OFF \
    -DExamples=OFF
  - make -j3 install

  # Build, test and install pomerol2triqs
  - cd $TRAVIS_BUILD_DIR/..
  - mkdir pomerol2triqs_installed
  - mkdir pomerol2triqs.build && pushd pomerol2triqs.build
  - |
    cmake ../pomerol2triqs \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../pomerol2triqs_installed \
    -DCMAKE_CXX_COMPILER=/usr/bin/${CXX} \
    -DTRIQS_ROOT=$PREREQS_DIR \
    -DPOMEROL_PATH=$PREREQS_DIR
  - make -j3
  - make test
  - make install

